--LANGUAGE = MySQL
SELECT * FROM
	(SELECT CONCAT(NAME,'(',LEFT(OCCUPATION,1),')') as 'a'
	FROM OCCUPATIONS
	ORDER BY NAME) x
UNION ALL

SELECT * FROM
	(SELECT CONCAT('There are a total of ', num, ' ', LOWER(OCCUPATION),'s.') as 'a'
	FROM 
		(SELECT COUNT(NAME) as num, 
			OCCUPATION 
		From OCCUPATIONS 
		GROUP BY OCCUPATION) ag
	ORDER BY num, OCCUPATION) y
ORDER BY a
